baseURL: "http://jeha00.github.io/"
title: "Jeha DevLog"
paginate: 7
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: "JeHa00 DevLog"
  description: "ì„ í•œ ë§ˆìŒê³¼ ê¾¸ì¤€í•¨ì´ ë¹„ë²”í•¨ì„ ë§Œë“ ë‹¤"
  keywords: [Blog, Portfolio, PaperMod]
  author: ["Me"] # multiple authors
  images: /apple-touch-icon.png
  DateFormat: "January 2, 2006"
  defaultTheme: light # dark, light
  disableThemeToggle: false

  showCategory: True
  ShowReadingTime: false
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: True # ê¸€ ì•ˆì— Table of Contents í‘œì‹œ
  tocopen: false

  assets:
    disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: /favicon.ico
    favicon16x16:  /favicon-16x16.png
    favicon32x32:  /favicon-32x32.png
    apple_touch_icon:  /apple-touch-icon.png
    safari_pinned_tab:  /safari-pinned-tab.svg

  label:
    text: "@Jeha00"
    iconeUrl: /apple-touch-icon.png
    iconHeight: 35

  # profile-mode
  profileMode:
    enabled: false
     # needs to be explicitly set
    title: Jeha00 DevLog
    subtitle: "ì„ í•œ ë§ˆìŒê³¼ ê¾¸ì¤€í•¨ì´ ë¹„ë²”í•¨ì„ ë§Œë“ ë‹¤"
    imageUrl: /apple-touch-icon.png
    imageWidth: 120
    imageHeight: 120
    imageTitle: my image
    buttons:
      - name: About
        url: /me/
      - name: Github
        url: https://github.com/jeha00/
      - name: Archive
        url: /archives/

  # home-info mode
  homeInfoParams:
    Title: "Jeha DevLog"
    Content: '
  **ì„ í•œ ë§ˆìŒê³¼ ê¾¸ì¤€í•¨ì´ ë¹„ë²”í•¨ì„ ë§Œë“ ë‹¤**
    
    -   

    -  
    
    - ê¸°ìˆ ì€ ì„¸ìƒì„ ì´ë¡­ê²Œ í•˜ê¸° ìœ„í•´ ì¡´ì¬í•œë‹¤. 

    - ê¸°ìˆ ì„ ì‚¬ìš©í•˜ëŠ”ë° ì œì¼ ì¢‹ì€ ë°©ë²•ì€ ë¬¸ì œ í•´ê²°ì— ì‚¬ìš©í•˜ëŠ” ê²ƒì´ë‹¤.  
    
    - ë¬¸ì œ í•´ê²°ì€ ë¬¸ì œ ì •ì˜ì—ì„œ, ë¬¸ì œ ì •ì˜ëŠ” ì°½ì˜ì„±ì—ì„œ, ì°½ì˜ì„±ì€ íƒ„íƒ„í•œ ê¸°ë³¸ì—ì„œ ì‹œì‘ëœë‹¤.   
    
    -

    - ê·¸ë¦¬ê³  ì´ ê¸°ë³¸ì€ ê¾¸ì¤€í•œ ë…¸ë ¥ìœ¼ë¡œ í˜•ì„±ëœë‹¤. ğŸŒ±  ğŸŒ³
    '
    

  socialIcons:
    - name: github
      url: "https://github.com/jeha00"
    - name: linkedin
      url: "https://www.linkedin.com/in/jeha-kim-b62897233/"

  analytics:
    google:
      SiteVerificationTag: "XYZabc"
    bing:
      SiteVerificationTag: "XYZabc"
    yandex:
      SiteVerificationTag: "XYZabc"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: false # hide on list pages and home
    hiddenInSingle: true # hide on single page

  # editPost:
  #   URL: "https://github.com/JeHa00/blog/content"
  #   Text: "Suggest Changes" # edit text
  #   appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    - name: About
      url: /me/
      weight: 10
    - name: Archive
      url: /archives/
      weight: 30
    - name: Categories
      url: /categories/
      weight: 40
    - name: Search
      url: /search/
      weight: 50

outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary

# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
# pygmentsUseClasses: true

markup:
    highlight:
        # anchorLineNos: true
        codeFences: true 
        guessSyntax: false
        lineNos: true
        style: monokai



